name: inventory
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  connectivity_plus: ^6.1.3
  data_table_2: 2.5.10
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  ffi: ^2.1.3
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  multi_dropdown: ^3.0.1
  path_provider: ^2.1.4
  pdf: ^3.11.2
  printing: ^5.13.4
  syncfusion_flutter_signaturepad: ^27.2.5
  flutter_native_splash: ^2.4.4
  excel: ^4.0.6
  flutter_single_instance: ^1.2.3
  file_picker: ^9.1.0
  path: ^1.9.0
  # permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/fonts/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700  
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/SegoeUI.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
    - family: SharpGrotesk
      fonts:
        - asset: assets/fonts/SharpGrotesk-Medium1.otf
          weight: 400
        - asset: assets/fonts/SharpGrotesk-Medium2.otf
          weight: 500

flutter_native_splash:
  image: assets/images/logo_white.jpg
  color: "#FFFFFF"