name: inventory
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  data_table_2: ^2.5.18
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_to_pdf: ^0.2.0
  get: ^4.6.6
  get_storage: ^2.1.1
  path_provider: ^2.1.4
  syncfusion_flutter_signaturepad: ^27.2.5
  widgets_to_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700  
